version: "3.8"

name: "Testing"

services:
  postgres_db:
    restart: always
    image: postgres
    container_name: testing_postgres
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - testing_postgres_volume:/var/lib/postgresql/data/pgdata
    networks:
      - testing_postgres_net

  rabbitmq:
    image: rabbitmq:management
    container_name: testing_message_broker
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - message_broker_net

  redis:
    image: redis/redis-stack:latest
    container_name: testing_redis_om
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    networks:
      - redis_net

networks:
  testing_postgres_net:
    driver: bridge
  message_broker_net:
    driver: bridge
  redis_net:
    driver: bridge

volumes:
  testing_postgres_volume:
    driver: local