<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Authorization.Contracts\Authorization.Contracts.csproj" />
    <ProjectReference Include="..\Authorization.Domain\Authorization.Domain.csproj" />
    
	<ProjectReference Include="..\..\Application.Shared\Application.Shared.csproj" />
    <ProjectReference Include="..\..\Notification\Notification.Contracts\Notification.Contracts.csproj" />
    <ProjectReference Include="..\..\Test\Test.Contracts\Test.Contracts.csproj" />
    <ProjectReference Include="..\..\TestRating\TestRating.Contracts\TestRating.Contracts.csproj" />
  </ItemGroup>

</Project>
