<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Test.Contracts\Test.Contracts.csproj" />
    <ProjectReference Include="..\Test.Domain\Test.Domain.csproj" />
	  
    <ProjectReference Include="..\..\Application.Shared\Application.Shared.csproj" />
    <ProjectReference Include="..\..\Notification\Notification.Contracts\Notification.Contracts.csproj" />
    <ProjectReference Include="..\..\Authorization\Authorization.Contracts\Authorization.Contracts.csproj" />
  </ItemGroup>

</Project>
