server {
  listen  6000;
  listen  6002 ssl;
  server_name  localhost;
  ssl_certificate /etc/certs/cert.crt;
  ssl_certificate_key /etc/certs/key.key;

  
  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    try_files $uri /index.html;
  }
}